### ISSUE TITLE
Restrict Valid Operators Based on Field Type

### ISSUE THREAD

**Issue by mrname** [modlinltd/django-advanced-filters#75] opened 2018-06-11 19:20 UTC
As of right now, all operators are available regardless of the field type. For instance, the admin section would allow you to choose the "Equals" or "Greater Than" operators for a boolean field. It would be great if the UI would only present appropriate operators based on the field type. I am not certain as to whether this is something I could already implement in my admin class, or if this should be a feature request, in which case I am happy to look into whipping up a PR. Thanks!

**Comment by asfaltboy** [comment] 2018-06-11 20:43
Thanks for the contribution @mrname ! This seems like this feature request is a dupe of #23, which also has some inspiration sources. Please have a look and let reopen this ticket if differs. 
And yes, we really ❤️PRs!

**Closed by asfaltboy** 2018-06-11 20:43 UTC
