### ISSUE TITLE
'grp_tags' is not a valid tag library

### ISSUE THREAD

**Issue by kouroshparsa** [modlinltd/django-advanced-filters#15] opened 2016-03-19 07:22 UTC
I'm using django-advanced-filters with django 1.8 on python2.7 django-advanced-filters==1.0.1 django-braces==1.4.0 django-easy-select2==1.2.5.
It works fine, but when I try to modify a filter, it fails.
Full bug details are at:
http://stackoverflow.com/questions/36098971/django-advanced-filters-grp-tags-is-not-a-valid-tag-library

I even tried making the advanced_filter_fields simpler but it still fails to modify it.
I really hope you can fix this or provide a workaround.
thanks

**Comment by asfaltboy** [comment] 2016-03-19 07:43
Duplicate of #7 , fixed in `develop` branch.

**Closed by asfaltboy** 2016-03-19 07:43 UTC
