### ISSUE TITLE
'AdvancedFilterQueryForm' object has no attribute 'cleaned_data'

### ISSUE THREAD

**Issue by DuSheridan** [modlinltd/django-advanced-filters#141] opened 2021-04-26 08:01 UTC
#### Describe the bug
Trying to create any new filter leads to `AdvancedFilterQueryForm object has no attribute cleaned_data` error.

#### Steps to reproduce
-  Have Django 3.2.0 installed
-  Try creating a filter

#### Expected behaviour
You should be able to create a filter

#### Details
- OS: Windows 10/Alpine Linux v3.13
- Python version 3.7/3.8	
- Django version 3.2.0 
- django-advanced-filters version 1.3.0
- Browser Chrome

**Comment by Nader-Blnk** [comment] 2021-05-18 10:14
@DuSheridan  Did you solve it?, I am facing the same problem

**Comment by DuSheridan** [comment] 2021-05-18 10:28
@Nader-Blnk I've side-stepped the issue by downgrading django to 3.1.3, haven't really looked into it since.

**Comment by theLastOfCats** [comment] 2021-07-12 16:57
Looks like it's broken starting after merging this PR
https://github.com/django/django/pull/13627

**Comment by vineetg3** [comment] 2021-08-10 16:47
I'm facing the same issue, with django 3.2.2

**Comment by DavidCrediverso** [comment] 2021-08-31 04:35
same problem :(

**Comment by tovfikur** [comment] 2021-09-12 12:49
Same problem :(

**Comment by urfinorg** [comment] 2021-09-13 08:25
As i can see, this issue starting from Django 3.2. I can`t reprodusing it on 3.1.13(last version of 3.1 branch).

**Comment by hzung** [comment] 2021-11-02 11:41
I finally fix the above issue by adding these codes in the source and installing the extension by

```
cd django-advanced-filters
python3 setup.py install
```

Thanks for the code of @urfinorg

Here is the PR: https://github.com/modlinltd/django-advanced-filters/pull/153/files
I can create a new filter or update the filter now. I don't know if there is any drawback to this fix. But at least It works for now

**Comment by taut-and-yare** [comment] 2022-02-18 14:05
This seems to be fixed in the develop branch?! 
@DuSheridan any plans for a PyPI release that fixes this?

**Comment by Aref20** [comment] 2022-06-22 08:49
Do you fix it?

**Comment by davidfstr** [comment] 2022-06-22 12:32
Recent maintainers @asfaltboy and @hugovk , **this issue prevents the use of django-advanced-filters on Django 3.2+**. 

My understanding is that [a fix has been merged to the develop branch](https://github.com/modlinltd/django-advanced-filters/issues/141#issuecomment-1044580204) but no release has been issued to PyPI with the fix. **Any chance one of you could cut a release** so that django-advanced-filters can be used on modern Django versions?

**Comment by hugovk** [comment] 2022-06-22 13:56
@davidfstr Hi! I'm not a maintainer here, just contributed a [PR](https://github.com/modlinltd/django-advanced-filters/pull/151) :)

Only @asfaltboy is listed as the PyPI maintainer https://pypi.org/project/django-advanced-filters/, hopefully he can make a release soon.

**Comment by asfaltboy** [comment] 2022-06-27 08:12
Thanks for the kind reminder, since this version contains a breaking change (dropping support for older Python/Django versions), it's released [as 2.0.0 on pypi](https://pypi.org/project/django-advanced-filters/2.0.0/).

**Comment by DmytroLitvinov** [comment] 2022-06-27 11:43
Hi @asfaltboy ,

Good news. May you also take a look at related PR for that issue? https://github.com/modlinltd/django-advanced-filters/pull/153

Maybe we can merge it and release to PyPI also?

**Comment by asfaltboy** [comment] 2022-09-25 09:59
@DmytroLitvinov we're saying the validation issue is not fixed in 2.0 ? Can you provide some more details on what used to happen and what doesn't happen now? Would it previously let you create a filter without any value in the value field, or would it raise a validation error, and now doesn't?

**Comment by DmytroLitvinov** [comment] 2022-09-26 03:27
Hi @asfaltboy , 
It was reported by my colleague so I just let you know about taking a look. In our case we reused library for our own needs.

**Comment by asfaltboy** [comment] 2022-10-08 18:25
I wasn't able to reproduce this particular issue as described above in 2.0. I'm going to go ahead and close the issue. If there are any concerns, please let me know. If there's still some issue, kindly provide step-by-step instructions on how to reproduce the issue. And please forgive me If I missed something obvious

**Closed by asfaltboy** 2022-10-08 18:25 UTC
